from pathlib import Path

p=Path('app.py')
s=p.read_text(encoding='utf-8')

old_init='''init()\n\n_platform=st.segmented_control("Platform",options=["DK","FD"],format_func=lambda x: "DraftKings" if x=="DK" else "FanDuel",default=st.session_state.get("dfs_site","DK"),key="hub_platform") or "DK"'''
new_init='''init()\n\n# Workspace restore may need to switch platforms. Apply that saved platform BEFORE\n# the segmented-control widget is created so Streamlit does not interpret the\n# restored workspace as a user platform switch and clear Saved Lineups.\n_pending_workspace_site=st.session_state.pop("nuke_hub_workspace_site_pending",None)\nif _pending_workspace_site in ["DK","FD"]:\n    st.session_state["dfs_site"]=_pending_workspace_site\n    st.session_state["hub_platform"]=_pending_workspace_site\n\n_platform=st.segmented_control("Platform",options=["DK","FD"],format_func=lambda x: "DraftKings" if x=="DK" else "FanDuel",default=st.session_state.get("dfs_site","DK"),key="hub_platform") or "DK"'''
if old_init in s:
    s=s.replace(old_init,new_init,1)
elif 'nuke_hub_workspace_site_pending' not in s:
    raise SystemExit('platform anchor not found')

old_ws='''def workspace():\n    return json.dumps({"slate_name":st.session_state.slate_name,"pool_ids":list(st.session_state.pool_ids),"lineups":st.session_state.lineups,"saved_lineups":st.session_state.saved_lineups,"draft_saved_link":st.session_state.draft_saved_link,"qb_plan":st.session_state.qb_plan,"qb_slot_map":st.session_state.qb_slot_map,"projection_overrides":st.session_state.projection_overrides},indent=2)\n\ndef restore(o):\n    arr=o.get("lineups",[])[:MAX_LU]\n    while len(arr)<MAX_LU:arr.append(empty_lu())\n    st.session_state.lineups=arr\n    st.session_state.pool_ids=set(o.get("pool_ids",[]))\n    st.session_state.saved_lineups=o.get("saved_lineups",{})\n    st.session_state.draft_saved_link=o.get("draft_saved_link",{})\n    st.session_state.qb_plan=o.get("qb_plan",{})\n    st.session_state.qb_slot_map=o.get("qb_slot_map",{})\n    st.session_state.projection_overrides=o.get("projection_overrides",{})\n    st.session_state.model_df=None\n    st.session_state.pending_pool_ids=set(st.session_state.pool_ids)'''
new_ws='''def workspace():\n    return json.dumps({\n        "product":"NUKE NFL DFS HUB",\n        "workspace_version":2,\n        "dfs_site":st.session_state.get("dfs_site",SITE),\n        "slate_name":st.session_state.slate_name,\n        "pool_ids":list(st.session_state.pool_ids),\n        "lineups":st.session_state.lineups,\n        "saved_lineups":st.session_state.saved_lineups,\n        "draft_saved_link":st.session_state.draft_saved_link,\n        "qb_plan":st.session_state.qb_plan,\n        "qb_slot_map":st.session_state.qb_slot_map,\n        "projection_overrides":st.session_state.projection_overrides,\n        "current_lu":st.session_state.get("current_lu",0),\n        "active_build_slot":st.session_state.get("active_build_slot",0),\n        "slot":st.session_state.get("slot","QB"),\n        "multi_view":st.session_state.get("multi_view",1),\n        "combo_threshold":st.session_state.get("combo_threshold",35),\n    },indent=2)\n\ndef restore(o):\n    arr=o.get("lineups",[])[:MAX_LU]\n    while len(arr)<MAX_LU:arr.append(empty_lu())\n    saved=dict(o.get("saved_lineups",{}) or {})\n    st.session_state.lineups=arr\n    st.session_state.pool_ids=set(o.get("pool_ids",[]))\n    st.session_state.saved_lineups=saved\n    st.session_state.draft_saved_link=dict(o.get("draft_saved_link",{}) or {})\n    st.session_state.qb_plan=dict(o.get("qb_plan",{}) or {})\n    st.session_state.qb_slot_map=dict(o.get("qb_slot_map",{}) or {})\n    st.session_state.projection_overrides=dict(o.get("projection_overrides",{}) or {})\n    st.session_state.current_lu=int(o.get("current_lu",0) or 0)\n    st.session_state.active_build_slot=int(o.get("active_build_slot",0) or 0)\n    st.session_state.slot=str(o.get("slot","QB") or "QB")\n    st.session_state.multi_view=int(o.get("multi_view",1) or 1)\n    st.session_state.combo_threshold=int(o.get("combo_threshold",35) or 35)\n    saved_site=str(o.get("dfs_site",st.session_state.get("dfs_site","DK"))).upper()\n    if saved_site in ["DK","FD"]:\n        st.session_state["nuke_hub_workspace_site_pending"]=saved_site\n    st.session_state["nuke_hub_workspace_loaded_saved_count"]=len(saved)\n    st.session_state.model_df=None\n    st.session_state.pending_pool_ids=set(st.session_state.pool_ids)'''
if old_ws in s:
    s=s.replace(old_ws,new_ws,1)
elif '"workspace_version":2' not in s:
    raise SystemExit('workspace function anchor not found')

old_sidebar='''    wup=st.file_uploader("Load workspace",type="json")\n    if wup is not None and st.button("Restore workspace"):\n        try:restore(json.load(wup));st.success("Restored");st.rerun()\n        except Exception as e:st.error(str(e))\n    st.download_button("Save workspace",workspace(),"nuke_workspace.json","application/json",use_container_width=True)'''
new_sidebar='''    wup=st.file_uploader("Load workspace",type="json")\n    if wup is not None and st.button("Restore workspace"):\n        try:\n            restore(json.load(wup))\n            st.rerun()\n        except Exception as e:\n            st.error(str(e))\n    restored_saved=st.session_state.pop("nuke_hub_workspace_loaded_saved_count",None)\n    if restored_saved is not None:\n        st.success(f"Workspace restored · {int(restored_saved)} Saved Lineup{'s' if int(restored_saved)!=1 else ''} loaded")\n    st.download_button("Save workspace",workspace(),"nuke_workspace.json","application/json",use_container_width=True)'''
if old_sidebar in s:
    s=s.replace(old_sidebar,new_sidebar,1)
elif 'Workspace restored ·' not in s:
    raise SystemExit('sidebar workspace anchor not found')

p.write_text(s,encoding='utf-8')
print('patched Hub workspace saved-lineup restore')
