from pathlib import Path

p=Path('pages/6_SIM.py')
s=p.read_text()
old='''    with tab7:\n        st.subheader(f"📤 {cfg.name} Lineup Export")\n        source_options=["Portfolio","Contest-ranked","NUKEM-ranked"]\n        export_source=st.selectbox("Lineup source",source_options,index=0,key=f"export_source_{site}")\n        export_results=portfolio if export_source=="Portfolio" and portfolio is not None and not portfolio.empty else contest_results if export_source=="Contest-ranked" and contest_results is not None and not contest_results.empty else results\n        max_export=min(150,len(export_results))\n        export_count=st.number_input("Lineups to export",1,max_export,min(150,max_export),1,key=f"export_count_{site}")\n        lineup_only=build_lineup_only_csv(sim_players,export_results,int(export_count),site=site)\n        short_site="fd" if site=="FD" else "dk"\n        st.download_button(f"Download {cfg.name} lineup-only CSV",lineup_only,f"nuke_{short_site}_lineups.csv","text/csv")\n        entries_upload=st.file_uploader(f"Upload your {cfg.name} Entries CSV",type=["csv"],key=f"entries_upload_{site}")\n        if entries_upload is not None:\n            try:\n                filled,info=fill_entries_csv(entries_upload.getvalue(),sim_players,export_results,int(export_count),site=site)\n                st.success(f"Filled {info['entries_filled']} {cfg.name} entries.")\n                st.download_button(f"⬇️ Download {cfg.name} Upload CSV",filled,f"nuke_{short_site}_upload.csv","text/csv",type="primary")\n            except Exception as e:\n                st.error(f"Could not build {cfg.name} upload file: {e}")\n'''
new='''    with tab7:\n        export_platform_name="FanDuel" if site=="FD" else "DraftKings"\n        st.subheader(f"📤 {export_platform_name} Lineup Export")\n        source_options=["Portfolio","Contest-ranked","NUKEM-ranked"]\n        export_source=st.selectbox("Lineup source",source_options,index=0,key=f"export_source_{site}")\n        export_results=portfolio if export_source=="Portfolio" and portfolio is not None and not portfolio.empty else contest_results if export_source=="Contest-ranked" and contest_results is not None and not contest_results.empty else results\n        max_export=min(150,len(export_results))\n        export_count=st.number_input("Lineups to export",1,max_export,min(150,max_export),1,key=f"export_count_{site}")\n        lineup_only=build_lineup_only_csv(sim_players,export_results,int(export_count),site=site)\n        short_site="fd" if site=="FD" else "dk"\n        st.download_button(f"Download {export_platform_name} lineup-only CSV",lineup_only,f"nuke_{short_site}_lineups.csv","text/csv")\n        entries_upload=st.file_uploader(f"Upload your {export_platform_name} Entries CSV",type=["csv"],key=f"entries_upload_{site}")\n        if entries_upload is not None:\n            try:\n                filled,info=fill_entries_csv(entries_upload.getvalue(),sim_players,export_results,int(export_count),site=site)\n                st.success(f"Filled {info['entries_filled']} {export_platform_name} entries.")\n                st.download_button(f"⬇️ Download {export_platform_name} Upload CSV",filled,f"nuke_{short_site}_upload.csv","text/csv",type="primary")\n            except Exception as e:\n                st.error(f"Could not build {export_platform_name} upload file: {e}")\n'''
if old not in s:
    raise RuntimeError('export block not found')
s=s.replace(old,new,1)
p.write_text(s)
print('patched export block')
