from pathlib import Path
p=Path('pages/6_SIM.py')
s=p.read_text(encoding='utf-8')
old='''    min_salary=st.number_input("Minimum salary",cfg.min_salary_input,cfg.max_salary_input,cfg.default_min_salary,100,key=f"min_salary_{site}")\n    flex_position="ANY"\n    if site=="FD":\n        flex_position=st.selectbox(\n            "FLEX position", ["ANY","RB","WR","TE"], index=0, key="nuke_fd_flex_position",\n            help="FanDuel only. Choose RB to force every generated lineup to use a running back in FLEX (3 RB total). Changing this requires a new NUKE SIM run."\n        )\n    no_offense_vs_dst=st.checkbox(\n        "No players vs opposing defense", value=True, key="nuke_no_offense_vs_dst",\n        help="DraftKings and FanDuel. When checked, if a defense is selected, NUKE will not use any QB/RB/WR/TE from that defense's opponent in the same lineup. Changing this requires a new NUKE SIM run."\n    )\n'''
new='''    min_salary=st.number_input("Minimum salary",cfg.min_salary_input,cfg.max_salary_input,cfg.default_min_salary,100,key=f"min_salary_{site}")\n    st.markdown("**LINEUP RULES**")\n    no_offense_vs_dst=st.checkbox(\n        "No players vs opposing defense", value=True, key="nuke_no_offense_vs_dst",\n        help="DraftKings and FanDuel. When checked, if a defense is selected, NUKE will not use any QB/RB/WR/TE from that defense's opponent in the same lineup. Changing this requires a new NUKE SIM run."\n    )\n    flex_position="ANY"\n    if site=="FD":\n        flex_position=st.selectbox(\n            "FLEX position", ["ANY","RB","WR","TE"], index=0, key="nuke_fd_flex_position",\n            help="FanDuel only. Choose RB to force every generated lineup to use a running back in FLEX (3 RB total). Changing this requires a new NUKE SIM run."\n        )\n'''
if old not in s:
    raise SystemExit('sidebar target block not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
