from pathlib import Path
p=Path('nuke_sim.py')
s=p.read_text(encoding='utf-8')
old='''            qbids=pools["QB"]; qw=w[qbids]/w[qbids].sum(); qb=int(rng.choice(qbids,p=qw))\n            nmates,nbring=stack_shapes[int(rng.choice(5,p=shape_probs/shape_probs.sum()))]; mates,opp=qb_cache[qb]\n            if len(mates)<nmates or len(opp)<nbring:continue\n            chosen=[qb]\n            if nmates:\n                mw=w[mates]; chosen+=list(map(int,rng.choice(mates,nmates,replace=False,p=mw/mw.sum())))\n            if nbring:\n                avail=opp[~np.isin(opp,chosen)];\n                if len(avail)<nbring:continue\n                ow=w[avail]; chosen+=list(map(int,rng.choice(avail,nbring,replace=False,p=ow/ow.sum())))\n'''
new='''            chosen=list(locked)\n            fallback_locked_qbs=[i for i in chosen if pos[i]=="QB"]\n            if fallback_locked_qbs:\n                qb=int(fallback_locked_qbs[0])\n                if not bool(qbmask[qb]): continue\n            else:\n                qbids=pools["QB"]; qw=w[qbids]/w[qbids].sum(); qb=int(rng.choice(qbids,p=qw)); chosen.append(qb)\n            nmates,nbring=stack_shapes[int(rng.choice(5,p=shape_probs/shape_probs.sum()))]; mates,opp=qb_cache[qb]\n            have_mates=sum((team[i]==team[qb]) and (pos[i] in {"WR","TE"}) for i in chosen)\n            have_bring=sum((game[i]==game[qb]) and (team[i]!=team[qb]) and (pos[i] in {"RB","WR","TE"}) for i in chosen)\n            need_mates=max(0,nmates-have_mates); need_bring=max(0,nbring-have_bring)\n            avail_mates=mates[~np.isin(mates,chosen)]\n            if len(avail_mates)<need_mates:continue\n            if need_mates:\n                mw=w[avail_mates]; chosen+=list(map(int,rng.choice(avail_mates,need_mates,replace=False,p=mw/mw.sum())))\n            avail=opp[~np.isin(opp,chosen)]\n            if len(avail)<need_bring:continue\n            if need_bring:\n                ow=w[avail]; chosen+=list(map(int,rng.choice(avail,need_bring,replace=False,p=ow/ow.sum())))\n'''
if old not in s:
    raise SystemExit('fallback block not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
