from pathlib import Path
p=Path('nuke_sim.py')
s=p.read_text(encoding='utf-8')
old='''    seen=[]; keys=set(); attempts=0; target=max(60000,int(n_lineups)*320); player_counts=np.zeros(len(p),dtype=float)\n    while len(seen)<int(n_lineups) and attempts<target:\n        attempts+=1\n        profile_i=int(rng.choice(len(profiles),p=profile_probs)); profile,_,market_power,crowd_strength,shape_probs=profiles[profile_i]\n        base=np.power(.08+market,market_power)*np.clip(usage,.35,2.25)*np.clip(auto,.18,1.15)*np.exp(.34*gen_boost)\n        if len(seen):\n            exposure=player_counts/max(1,len(seen)); crowd=np.exp(-crowd_strength*np.clip(exposure-.18,0,None)*4.0)\n            base*=crowd\n        if profile=="Leverage":\n            base*=np.power(np.clip(1.20-market,.20,1.20),.35)\n        elif profile=="Correlated":\n            base*=np.clip(.70+.55*auto,.25,1.25)\n        w=np.clip(base,1e-10,None)\n'''
new='''    # Cache the static portion of each profile's player weights. Previously this\n    # was recomputed on every rejected lineup attempt.\n    profile_bases=[]\n    for profile,_,market_power,_,_ in profiles:\n        base=np.power(.08+market,market_power)*np.clip(usage,.35,2.25)*np.clip(auto,.18,1.15)*np.exp(.34*gen_boost)\n        if profile=="Leverage":\n            base*=np.power(np.clip(1.20-market,.20,1.20),.35)\n        elif profile=="Correlated":\n            base*=np.clip(.70+.55*auto,.25,1.25)\n        profile_bases.append(np.clip(base,1e-10,None))\n\n    seen=[]; keys=set(); attempts=0; target=max(20000,int(n_lineups)*160); player_counts=np.zeros(len(p),dtype=float)\n    while len(seen)<int(n_lineups) and attempts<target:\n        attempts+=1\n        profile_i=int(rng.choice(len(profiles),p=profile_probs)); profile,_,market_power,crowd_strength,shape_probs=profiles[profile_i]\n        w=profile_bases[profile_i].copy()\n        if len(seen):\n            exposure=player_counts/max(1,len(seen)); crowd=np.exp(-crowd_strength*np.clip(exposure-.18,0,None)*4.0)\n            w*=crowd\n        w=np.clip(w,1e-10,None)\n'''
if old not in s: raise SystemExit('weight block not found')
s=s.replace(old,new,1)
old2='''        while len(chosen)<9:\n            ids=flex[~np.isin(flex,chosen)]\n            if not len(ids):break\n            fw=w[ids]/w[ids].sum(); chosen.append(int(rng.choice(ids,p=fw)))\n        if len(chosen)!=9:continue\n\n        arr=np.asarray(chosen,dtype=int); total=int(sal[arr].sum()); key=tuple(sorted(chosen))\n        if total<min_salary or total>50000 or key in keys or not _valid_lineup(chosen,p,min_salary):continue\n'''
new2='''        # Salary-aware final FLEX selection. The old engine picked FLEX blindly and\n        # then rejected almost every lineup outside the narrow $49.4K-$50K band.\n        # Restricting the final draw to players that can legally complete the lineup\n        # preserves the same weighted player selection while eliminating wasted attempts.\n        while len(chosen)<9:\n            ids=flex[~np.isin(flex,chosen)]\n            if not len(ids):break\n            current_salary=int(sal[np.asarray(chosen,dtype=int)].sum())\n            need_low=min_salary-current_salary; need_high=50000-current_salary\n            ids=ids[(sal[ids]>=need_low)&(sal[ids]<=need_high)]\n            if not len(ids):break\n            fw=w[ids]/w[ids].sum(); chosen.append(int(rng.choice(ids,p=fw)))\n        if len(chosen)!=9:continue\n\n        arr=np.asarray(chosen,dtype=int); total=int(sal[arr].sum()); key=tuple(sorted(chosen))\n        if total<min_salary or total>50000 or key in keys:continue\n'''
if old2 not in s: raise SystemExit('flex block not found')
s=s.replace(old2,new2,1)
p.write_text(s,encoding='utf-8')
