from pathlib import Path

# --- Optimize portfolio engine ---
p=Path('nuke_portfolio.py')
s=p.read_text(encoding='utf-8')
s=s.replace('PORTFOLIO_ENGINE_VERSION = "Portfolio Engine V5.2"','PORTFOLIO_ENGINE_VERSION = "Portfolio Engine V5.3"')
s=s.replace('''    path_series = x.get("Strongest Path", pd.Series(["UNKNOWN"] * n)).fillna("UNKNOWN").astype(str)\n    qb_series = x.get("QB", pd.Series(["UNKNOWN"] * n)).fillna("UNKNOWN").astype(str)\n    stack_series = x.get("Stack", pd.Series(["UNKNOWN"] * n)).fillna("UNKNOWN").astype(str)\n    lineup_ids = [list(map(int, lu)) for lu in x["_indices"]] if "_indices" in x.columns else [[] for _ in range(n)]\n    lineup_teams, lineup_games = _lineup_team_game_sets(players, lineup_ids)\n''','''    path_series = x.get("Strongest Path", pd.Series(["UNKNOWN"] * n)).fillna("UNKNOWN").astype(str)\n    qb_series = x.get("QB", pd.Series(["UNKNOWN"] * n)).fillna("UNKNOWN").astype(str)\n    stack_series = x.get("Stack", pd.Series(["UNKNOWN"] * n)).fillna("UNKNOWN").astype(str)\n    path_arr = path_series.to_numpy(str)\n    qb_arr = qb_series.to_numpy(str)\n    stack_arr = stack_series.to_numpy(str)\n    lineup_ids = [list(map(int, lu)) for lu in x["_indices"]] if "_indices" in x.columns else [[] for _ in range(n)]\n    lineup_sets = [set(lu) for lu in lineup_ids]\n    lineup_teams, lineup_games = _lineup_team_game_sets(players, lineup_ids)\n    lineup_pairs_cache = [list(itertools.combinations(sorted(st), 2)) for st in lineup_sets]\n    lineup_triples_cache = [list(itertools.combinations(sorted(st), 3)) for st in lineup_sets]\n    overlap_matrix = np.zeros((n, n), dtype=np.int8)\n    for i in range(n):\n        si = lineup_sets[i]\n        for j in range(i):\n            ov = len(si & lineup_sets[j])\n            overlap_matrix[i, j] = ov\n            overlap_matrix[j, i] = ov\n''')
s=s.replace('''    selected, path_counts, qb_counts, stack_counts = [], {}, {}, {}\n    player_counts, team_counts, game_counts, reasons = {}, {}, {}, {}\n    pair_counts, triple_counts = {}, {}\n\n    def lineup_pairs(lu):\n        return [tuple(sorted(x)) for x in itertools.combinations(sorted(set(lu)), 2)]\n\n    def lineup_triples(lu):\n        return [tuple(sorted(x)) for x in itertools.combinations(sorted(set(lu)), 3)]\n''','''    selected, path_counts, qb_counts, stack_counts = [], {}, {}, {}\n    selected_mask = np.zeros(n, dtype=bool)\n    player_counts, team_counts, game_counts, reasons = {}, {}, {}, {}\n    pair_counts, triple_counts = {}, {}\n''')
s=s.replace('''        qb = qb_series.iloc[i]\n''','''        qb = qb_arr[i]\n''')
s=s.replace('''            if i in selected or not exposure_ok(i):\n                continue\n\n            lu = lineup_ids[i]\n            path, qb, stack = path_series.iloc[i], qb_series.iloc[i], stack_series.iloc[i]\n            overlaps = [_overlap(lu, lineup_ids[j]) for j in selected]\n            worst_overlap = max(overlaps) if overlaps else 0\n            avg_overlap = float(np.mean(overlaps)) if overlaps else 0.0\n''','''            if selected_mask[i] or not exposure_ok(i):\n                continue\n\n            lu = lineup_ids[i]\n            path, qb, stack = path_arr[i], qb_arr[i], stack_arr[i]\n            if selected:\n                overlaps = overlap_matrix[i, selected]\n                worst_overlap = int(overlaps.max())\n                avg_overlap = float(overlaps.mean())\n            else:\n                worst_overlap = 0\n                avg_overlap = 0.0\n''')
s=s.replace('''            lu_pairs = lineup_pairs(lu)\n            lu_triples = lineup_triples(lu)\n''','''            lu_pairs = lineup_pairs_cache[i]\n            lu_triples = lineup_triples_cache[i]\n''')
s=s.replace('''            remaining = [i for i in range(n) if i not in selected and exposure_ok(i)]\n''','''            remaining = [i for i in range(n) if not selected_mask[i] and exposure_ok(i)]\n''')
s=s.replace('''        selected.append(best_i)\n        path, qb, stack = path_series.iloc[best_i], qb_series.iloc[best_i], stack_series.iloc[best_i]\n''','''        selected.append(best_i)\n        selected_mask[best_i] = True\n        path, qb, stack = path_arr[best_i], qb_arr[best_i], stack_arr[best_i]\n''')
s=s.replace('''        for core in lineup_pairs(lineup_ids[best_i]):\n            pair_counts[core] = pair_counts.get(core, 0) + 1\n        for core in lineup_triples(lineup_ids[best_i]):\n            triple_counts[core] = triple_counts.get(core, 0) + 1\n''','''        for core in lineup_pairs_cache[best_i]:\n            pair_counts[core] = pair_counts.get(core, 0) + 1\n        for core in lineup_triples_cache[best_i]:\n            triple_counts[core] = triple_counts.get(core, 0) + 1\n''')
s=s.replace('''    V5.2 keeps player/team/game caps and adds soft repeated pair / 3-player core control while retaining soft\n''','''    V5.3 preserves V5.2 portfolio logic while precomputing overlap/core structures for speed. It keeps player/team/game caps and soft repeated pair / 3-player core control while retaining soft\n''')
p.write_text(s,encoding='utf-8')

# --- Remove duplicate Run Performance UI ---
p=Path('pages/6_SIM.py')
s=p.read_text(encoding='utf-8')
s=s.replace('''stage_times=st.session_state.get("nuke_stage_times",{})\nstage_times=st.session_state.get("nuke_stage_times",{})\n''','''stage_times=st.session_state.get("nuke_stage_times",{})\n''')
block='''if stage_times:\n    st.subheader("⏱️ Run Performance")\n    total=float(st.session_state.get("nuke_sim_runtime",0.0))\n    timing_cols=st.columns(len(stage_times))\n    for col,(name,secs) in zip(timing_cols,stage_times.items()):\n        col.metric(name,f"{float(secs):.1f}s")\n    if total>0:\n        slow_name,slow_secs=max(stage_times.items(),key=lambda kv:kv[1])\n        st.caption(f"Total {total:.1f}s · Bottleneck: {slow_name} ({float(slow_secs):.1f}s, {100.0*float(slow_secs)/total:.0f}% of run).")\n\n'''
first=s.find(block)
second=s.find(block, first+1) if first!=-1 else -1
if second!=-1:
    s=s[:second]+s[second+len(block):]
p.write_text(s,encoding='utf-8')
