from pathlib import Path

page = Path('pages/13_SHOWDOWN_SIM.py')
sim = Path('nuke_showdown_sim.py')
ws = Path('nuke_showdown_workspace.py')

p = page.read_text(encoding='utf-8')
p = p.replace('from nuke_showdown import export_lineup_only_csv, parse_showdown_salary_csv\n', 'from nuke_showdown import export_lineup_only_csv, parse_showdown_salary_csv\nfrom nuke_showdown_fanduel import (\n    FANDUEL_SHOWDOWN_SALARY_CAP, export_fanduel_lineup_only_csv, parse_fanduel_showdown_csv,\n)\n', 1)
p = p.replace('DEFAULT_SHOWDOWN_CSV = Path(__file__).resolve().parents[1] / "data" / "showdown_current.csv"\n', 'DEFAULT_SHOWDOWN_CSV = Path(__file__).resolve().parents[1] / "data" / "showdown_current.csv"\nDEFAULT_FANDUEL_SHOWDOWN_CSV = Path(__file__).resolve().parents[1] / "data" / "showdown_fanduel_current.csv"\n', 1)

old_start = '''st.title("⚡ NUKE SHOWDOWN")\nst.caption("Projection-free DraftKings NFL single-game simulation · game scripts · Captain outcomes · portfolio generation")\n\nst.subheader("🏈 Current Game")\nwith st.expander("Optional: upload a different DraftKings Showdown salary CSV", expanded=False):\n    upload = st.file_uploader(\n        "Override current Showdown slate",\n        type=["csv"],\n        key="showdown_sim_upload",\n        help="Normally you do not need this. NUKE automatically loads the current bundled Showdown slate.",\n    )\n\ntry:\n    if upload is not None:\n        raw = pd.read_csv(upload)\n        source_label = f"Uploaded override: {upload.name}"\n    else:\n        if not DEFAULT_SHOWDOWN_CSV.exists():\n            st.error("The current Showdown slate is not available yet.")\n            st.stop()\n        raw = pd.read_csv(DEFAULT_SHOWDOWN_CSV)\n        source_label = "Loaded automatically"\n    players, meta = parse_showdown_salary_csv(raw)\nexcept Exception as exc:\n    st.error(f"Could not read this Showdown slate: {exc}")\n    st.stop()\n\nslate_sig = f"{meta['game_info']}|{len(players)}|{source_label}"\n'''
new_start = '''st.title("⚡ NUKE SHOWDOWN")\nsite = st.radio("Platform", ["DraftKings", "FanDuel"], horizontal=True, key="showdown_site")\nsite_key = "dk" if site == "DraftKings" else "fd"\nsalary_cap = 50000 if site == "DraftKings" else FANDUEL_SHOWDOWN_SALARY_CAP\nmultiplier_label = "CPT" if site == "DraftKings" else "MVP"\nflex_label = "FLEX" if site == "DraftKings" else "AnyFLEX"\nst.caption(f"Projection-free {site} NFL single-game simulation · game scripts · {multiplier_label} outcomes · portfolio generation")\n\nif st.session_state.get("showdown_last_site") != site:\n    st.session_state["showdown_last_site"] = site\n    st.session_state["showdown_min_salary"] = 42000 if site == "DraftKings" else 50000\n    st.session_state["showdown_max_salary"] = salary_cap\n    for _key in [\n        "showdown_sim_results", "showdown_sim_portfolio", "showdown_sim_players",\n        "showdown_sim_scripts", "showdown_sim_seed", "showdown_player_controls",\n        "showdown_construction_controls",\n    ]:\n        st.session_state.pop(_key, None)\n\nst.subheader("🏈 Current Game")\nwith st.expander(f"Optional: upload a different {site} Showdown salary CSV", expanded=False):\n    upload = st.file_uploader(\n        f"Override current {site} Showdown slate",\n        type=["csv"],\n        key=f"showdown_sim_upload_{site_key}",\n        help=f"Normally you do not need this. NUKE automatically loads the current bundled {site} single-game slate.",\n    )\n\ntry:\n    if upload is not None:\n        raw = pd.read_csv(upload)\n        source_label = f"Uploaded override: {upload.name}"\n    else:\n        default_csv = DEFAULT_SHOWDOWN_CSV if site == "DraftKings" else DEFAULT_FANDUEL_SHOWDOWN_CSV\n        if not default_csv.exists():\n            st.error(f"The current {site} Showdown slate is not available yet.")\n            st.stop()\n        raw = pd.read_csv(default_csv)\n        source_label = "Loaded automatically"\n    if site == "DraftKings":\n        players, meta = parse_showdown_salary_csv(raw)\n    else:\n        players, meta = parse_fanduel_showdown_csv(raw)\nexcept Exception as exc:\n    st.error(f"Could not read this {site} Showdown slate: {exc}")\n    st.stop()\n\nslate_sig = f"{site}|{meta['game_info']}|{len(players)}|{source_label}"\n'''
if old_start not in p:
    raise SystemExit('start block not found')
p = p.replace(old_start, new_start, 1)

p = p.replace('workspace_payload = showdown_workspace_bytes(st.session_state, meta["game_info"])', 'workspace_payload = showdown_workspace_bytes(st.session_state, meta["game_info"], site)', 1)
p = p.replace('file_name="nuke_showdown_workspace.json",', 'file_name=f"nuke_showdown_{site_key}_workspace.json",', 1)
p = p.replace('''            saved_slate = str(loaded_workspace.get("slate_label", "") or "")\n            current_slate = str(meta.get("game_info", "") or "")\n            if saved_slate and saved_slate != current_slate:\n''', '''            saved_slate = str(loaded_workspace.get("slate_label", "") or "")\n            saved_platform = str(loaded_workspace.get("platform", "") or "")\n            current_slate = str(meta.get("game_info", "") or "")\n            if saved_platform and saved_platform != site:\n                raise ValueError(f"This workspace is for {saved_platform}, but the current platform is {site}.")\n            if saved_slate and saved_slate != current_slate:\n''', 1)

p = p.replace('m3.metric("Format", "1 CPT + 5 FLEX")\nm4.metric("Cap", "$50,000")', 'm3.metric("Format", f"1 {multiplier_label} + 5 {flex_label}")\nm4.metric("Cap", f"${salary_cap:,}")', 1)
p = p.replace('"Salary": st.column_config.NumberColumn("FLEX", format="$%d", width="small"),', '"Salary": st.column_config.NumberColumn(flex_label, format="$%d", width="small"),', 1)

old_settings = '''    min_salary = s1.slider("Minimum salary", 30000, 50000, 42000, 100, key="showdown_min_salary")\n    max_salary = s2.slider(\n        "Maximum salary", 30000, 50000, 50000, 100, key="showdown_max_salary",\n        help="Set below $50,000 to intentionally leave salary unused and reduce duplicated Showdown constructions.",\n    )\n'''
new_settings = '''    salary_floor_min = 30000\n    min_salary = s1.slider("Minimum salary", salary_floor_min, salary_cap, 42000 if site == "DraftKings" else 50000, 100, key="showdown_min_salary")\n    max_salary = s2.slider(\n        "Maximum salary", salary_floor_min, salary_cap, salary_cap, 100, key="showdown_max_salary",\n        help=f"Set below ${salary_cap:,} to intentionally leave salary unused and reduce duplicated Showdown constructions.",\n    )\n'''
if old_settings not in p:
    raise SystemExit('settings salary block not found')
p = p.replace(old_settings, new_settings, 1)
p = p.replace('max_cpt = c6.slider("Max Captain exposure", 10, 100, 35, 5, key="showdown_max_cpt") / 100', 'max_cpt = c6.slider(f"Max {multiplier_label} exposure", 10, 100, 35, 5, key="showdown_max_cpt") / 100', 1)
p = p.replace('"Rushing Control · Chaos. Player outcomes use DraftKings salary/FPPG as baseline signals "', 'f"Rushing Control · Chaos. Player outcomes use {site} salary/FPPG as baseline signals "', 1)
p = p.replace('''            max_salary=max_salary,\n            seed=seed,\n''', '''            max_salary=max_salary,\n            salary_cap=salary_cap,\n            seed=seed,\n''', 1)

# Rename displayed CPT column to MVP for FanDuel without changing engine internals.
p = p.replace('''labeled = add_lineup_labels(results.head(250), sim_players)\nshow_cols = [\n    "CPT", "FLEX1", "FLEX2", "FLEX3", "FLEX4", "FLEX5", "Construction", "Salary",\n''', '''labeled = add_lineup_labels(results.head(250), sim_players)\nif site == "FanDuel":\n    labeled = labeled.rename(columns={"CPT": "MVP"})\nshow_cols = [\n    multiplier_label, "FLEX1", "FLEX2", "FLEX3", "FLEX4", "FLEX5", "Construction", "Salary",\n''', 1)
p = p.replace('''    p = add_lineup_labels(portfolio, sim_players)\n    st.dataframe(\n''', '''    p = add_lineup_labels(portfolio, sim_players)\n    if site == "FanDuel":\n        p = p.rename(columns={"CPT": "MVP"})\n    st.dataframe(\n''', 1)

# Make export platform-aware.
p = p.replace('st.markdown("#### 📤 DraftKings Export")\n    st.caption("Download this exact NUKE portfolio using the DraftKings CPT/FLEX player IDs from the current Showdown salary file.")', 'st.markdown(f"#### 📤 {site} Export")\n    st.caption(f"Download this exact NUKE portfolio using the {site} {multiplier_label}/{flex_label} player IDs from the current single-game salary file.")', 1)
p = p.replace('''            if salary > 50000:\n                raise ValueError(f"A portfolio lineup exceeds the DraftKings salary cap: ${salary:,}.")\n''', '''            if salary > salary_cap:\n                raise ValueError(f"A portfolio lineup exceeds the {site} salary cap: ${salary:,}.")\n''', 1)
p = p.replace('''                raise ValueError("A portfolio player could not be matched back to the current DraftKings salary file.")\n            if not str(cpt.get("CPT ID", "")).strip() or any(not str(x.get("FLEX ID", "")).strip() for x in flex):\n                raise ValueError("A DraftKings CPT/FLEX player ID is missing from the current salary file.")\n\n        dk_csv = export_lineup_only_csv(export_rows, players_by_key)\n    except Exception as exc:\n        export_error = str(exc)\n        dk_csv = None\n\n    if export_error:\n        st.error(f"DraftKings export is not ready: {export_error}")\n    else:\n        st.download_button(\n            "DOWNLOAD DK SHOWDOWN CSV",\n            data=dk_csv,\n            file_name="nuke_showdown_dk_portfolio.csv",\n            mime="text/csv",\n            type="primary",\n            use_container_width=True,\n            key="showdown_dk_export_download",\n        )\n        st.caption(f"{len(export_rows)} lineup{'s' if len(export_rows) != 1 else ''} ready for DraftKings upload.")\n''', '''                raise ValueError(f"A portfolio player could not be matched back to the current {site} salary file.")\n            if not str(cpt.get("CPT ID", "")).strip() or any(not str(x.get("FLEX ID", "")).strip() for x in flex):\n                raise ValueError(f"A {site} {multiplier_label}/{flex_label} player ID is missing from the current salary file.")\n\n        export_csv = export_lineup_only_csv(export_rows, players_by_key) if site == "DraftKings" else export_fanduel_lineup_only_csv(export_rows, players_by_key)\n    except Exception as exc:\n        export_error = str(exc)\n        export_csv = None\n\n    if export_error:\n        st.error(f"{site} export is not ready: {export_error}")\n    else:\n        st.download_button(\n            f"DOWNLOAD {'DK' if site == 'DraftKings' else 'FANDUEL'} SHOWDOWN CSV",\n            data=export_csv,\n            file_name=f"nuke_showdown_{site_key}_portfolio.csv",\n            mime="text/csv",\n            type="primary",\n            use_container_width=True,\n            key=f"showdown_{site_key}_export_download",\n        )\n        st.caption(f"{len(export_rows)} lineup{'s' if len(export_rows) != 1 else ''} ready for {site}.")\n''', 1)
p = p.replace('st.markdown("#### Captain Exposure")', 'st.markdown(f"#### {multiplier_label} Exposure")', 1)
page.write_text(p, encoding='utf-8')

s = sim.read_text(encoding='utf-8')
s = s.replace('def generate_showdown_candidates(players, max_candidates=12000, min_salary=42000, max_salary=SHOWDOWN_SALARY_CAP, seed=26):', 'def generate_showdown_candidates(players, max_candidates=12000, min_salary=42000, max_salary=SHOWDOWN_SALARY_CAP, salary_cap=SHOWDOWN_SALARY_CAP, seed=26):', 1)
s = s.replace('maximum = min(SHOWDOWN_SALARY_CAP, int(max_salary))', 'maximum = min(int(salary_cap), int(max_salary))', 1)
sim.write_text(s, encoding='utf-8')

w = ws.read_text(encoding='utf-8')
w = w.replace('def build_workspace(session_state, slate_label=""):', 'def build_workspace(session_state, slate_label="", platform=""):', 1)
w = w.replace('''        "slate_label": str(slate_label or ""),\n''', '''        "slate_label": str(slate_label or ""),\n        "platform": str(platform or ""),\n''', 1)
w = w.replace('def workspace_bytes(session_state, slate_label=""):\n    return json.dumps(\n        build_workspace(session_state, slate_label), indent=2, sort_keys=True\n', 'def workspace_bytes(session_state, slate_label="", platform=""):\n    return json.dumps(\n        build_workspace(session_state, slate_label, platform), indent=2, sort_keys=True\n', 1)
ws.write_text(w, encoding='utf-8')
