from pathlib import Path
p=Path('pages/6_SIM.py')
s=p.read_text(encoding='utf-8')
start=s.index('TAKE_LEVELS=[')
end=s.index('st.set_page_config', start)
s=s[:start]+'def boost_icon_state(value):\n    try:\n        level=max(-3,min(3,int(round(float(value)))))\n    except Exception:\n        level=0\n    return {\n        "⬇3": level == -3, "⬇2": level == -2, "⬇1": level == -1,\n        "⬆1": level == 1, "⬆2": level == 2, "⬆3": level == 3,\n    }\n\ndef icon_state_to_boost(row):\n    # One click is intended. If more than one is checked, strongest magnitude wins.\n    choices=[]\n    for col,val in (("⬇3",-3),("⬇2",-2),("⬇1",-1),("⬆1",1),("⬆2",2),("⬆3",3)):\n        try:\n            if bool(row[col]): choices.append(val)\n        except Exception:\n            pass\n    if not choices:\n        return 0.0\n    choices.sort(key=lambda x:(abs(x),x), reverse=True)\n    return float(choices[0])\n\n'+s[end:]
s=s.replace('Work the slate one game at a time. Include/remove players and choose a Take level from Hard Fade to Smash. Takes change candidate-lineup generation only — they do NOT change the player\'s simulated fantasy points.','Work the slate one game at a time. Include/remove players and click a boost/fade icon up to 3x. These clicks change candidate-lineup generation only — they do NOT change the player\'s simulated fantasy points.')
old='rows.append({"_row":int(idx),"_key":key,"Include":bool(cfg.get("include",True)),"Pos":row.Position,"Player":row.Name,"Salary":int(row.Salary),"Auto Role":row.auto_role,"Take":boost_to_take(cfg.get("boost",0.0)),"Role":str(cfg.get("role","AUTO")),"Usage x":float(cfg.get("usage",1.0))})'
new='icon_state=boost_icon_state(cfg.get("boost",0.0))\n                    rows.append({"_row":int(idx),"_key":key,"Include":bool(cfg.get("include",True)),"Pos":row.Position,"Player":row.Name,"Salary":int(row.Salary),"Auto Role":row.auto_role,**icon_state,"Role":str(cfg.get("role","AUTO")),"Usage x":float(cfg.get("usage",1.0))})'
s=s.replace(old,new)
s=s.replace('column_order=["Include","Pos","Player","Salary","Auto Role","Take","Role","Usage x"],','column_order=["Include","Pos","Player","Salary","Auto Role","⬇3","⬇2","⬇1","⬆1","⬆2","⬆3","Role","Usage x"],')
old_cfg='''                            "Take":st.column_config.SelectboxColumn("Take",options=TAKE_LEVELS,width="medium",help="Click a level: Hard Fade (-3), Fade (-2), Slight Fade (-1), Neutral, Boost (+1), Strong Boost (+2), or Smash (+3). Changes candidate generation only, not simulated fantasy points."),'''
new_cfg='''                            "⬇3":st.column_config.CheckboxColumn("⬇3",width="small",help="Hard fade (-3)"),\n                            "⬇2":st.column_config.CheckboxColumn("⬇2",width="small",help="Fade (-2)"),\n                            "⬇1":st.column_config.CheckboxColumn("⬇1",width="small",help="Slight fade (-1)"),\n                            "⬆1":st.column_config.CheckboxColumn("⬆1",width="small",help="Boost (+1)"),\n                            "⬆2":st.column_config.CheckboxColumn("⬆2",width="small",help="Strong boost (+2)"),\n                            "⬆3":st.column_config.CheckboxColumn("⬆3",width="small",help="Maximum boost (+3)"),'''
s=s.replace(old_cfg,new_cfg)
s=s.replace('updated_state[key]={"include":include,"boost":take_to_boost(erow["Take"]),"role":str(erow["Role"]),"usage":float(erow["Usage x"])}','updated_state[key]={"include":include,"boost":icon_state_to_boost(erow),"role":str(erow["Role"]),"usage":float(erow["Usage x"])}')
p.write_text(s,encoding='utf-8')
