from pathlib import Path

path=Path('app.py')
s=path.read_text(encoding='utf-8')

old='from fanduel_slate import load_fanduel_slate, FD_SLATE_LABEL\n'
new='from fanduel_slate import load_fanduel_slate, FD_SLATE_LABEL\nfrom nuke_odds import load_odds_history\n'
if 'from nuke_odds import load_odds_history' not in s:
    if old not in s:
        raise SystemExit('import anchor not found')
    s=s.replace(old,new,1)

anchor='def slate_overview():\n'
helper='''def opening_line_movements():\n    """Return the first recorded game total and team total for each slate market."""\n    h=load_odds_history()\n    if h is None or h.empty:\n        return {},{}\n    needed={"Team","Opponent","Snapshot UTC"}\n    if not needed.issubset(h.columns):\n        return {},{}\n    h=h.copy()\n    h["Team"]=h["Team"].astype(str).str.upper().str.strip()\n    h["Opponent"]=h["Opponent"].astype(str).str.upper().str.strip()\n    h=h.dropna(subset=["Snapshot UTC"])\n    h=h[(h["Team"]!="") & (h["Opponent"]!="")]\n    if h.empty:\n        return {},{}\n    h["GameKey"]=h.apply(lambda r:"|".join(sorted([r["Team"],r["Opponent"]])),axis=1)\n\n    game_open={}\n    if "Game Total" in h.columns:\n        for key,g in h.groupby("GameKey"):\n            g=g.sort_values("Snapshot UTC")\n            first_ts=g["Snapshot UTC"].iloc[0]\n            vals=pd.to_numeric(g.loc[g["Snapshot UTC"].eq(first_ts),"Game Total"],errors="coerce").dropna()\n            if not vals.empty:\n                game_open[key]=float(vals.median())\n\n    team_open={}\n    if "Team Total" in h.columns:\n        for (key,team),g in h.groupby(["GameKey","Team"]):\n            g=g.sort_values("Snapshot UTC")\n            first_ts=g["Snapshot UTC"].iloc[0]\n            vals=pd.to_numeric(g.loc[g["Snapshot UTC"].eq(first_ts),"Team Total"],errors="coerce").dropna()\n            if not vals.empty:\n                team_open[(key,team)]=float(vals.median())\n    return game_open,team_open\n\ndef format_total_movement(current,opening):\n    cur=float(current)\n    if opening is None or pd.isna(opening):\n        return f"{cur:g}"\n    delta=cur-float(opening)\n    if abs(delta)<0.05:\n        delta=0.0\n    return f"{cur:g} ({delta:+.1f})" if delta else f"{cur:g} (0.0)"\n\ndef movement_cell_style(value):\n    txt=str(value)\n    m=re.search(r"\\(([+-]?\\d+(?:\\.\\d+)?)\\)",txt)\n    if not m:\n        return ""\n    try:\n        delta=float(m.group(1))\n    except Exception:\n        return ""\n    if delta>0:\n        return "color:#19c37d;font-weight:800"\n    if delta<0:\n        return "color:#ff5d5d;font-weight:800"\n    return ""\n\n'''
if 'def opening_line_movements()' not in s:
    if anchor not in s:
        raise SystemExit('slate_overview anchor not found')
    s=s.replace(anchor,helper+anchor,1)

old_block='''    game_rank,team_rank,ng,nt=slate_total_ranks()\n\n    if ov["top_games"]:\n        left,right=st.columns([1.05,.95],gap="large")\n\n        with left:\n            st.markdown("#### Game Total Rankings")\n            rows=[]\n            for key,total in ov["top_games"]:\n                g=st.session_state.game_totals.get(key,{})\n                rows.append({\n                    "Rank":game_rank.get(key),\n                    "Game":f'{g.get("away","?")} @ {g.get("home","?")}',\n                    "Total":total\n                })\n            gdf=pd.DataFrame(rows)\n            st.dataframe(gdf,hide_index=True,use_container_width=True)\n\n        with right:\n            st.markdown("#### Implied Team Total Rankings")\n            rows=[]\n            for team,imp in ov["top_teams"]:\n                rows.append({\n                    "Rank":team_rank.get(team),\n                    "Team":team,\n                    "Implied Total":imp\n                })\n            tdf=pd.DataFrame(rows)\n            st.dataframe(tdf,hide_index=True,use_container_width=True)\n\n        st.caption("All ranks use only games and teams actually present in the selected platform slate.")\n'''
new_block='''    game_rank,team_rank,ng,nt=slate_total_ranks()\n    opening_games,opening_teams=opening_line_movements()\n\n    if ov["top_games"]:\n        left,right=st.columns([1.05,.95],gap="large")\n\n        with left:\n            st.markdown("#### Game Total Rankings")\n            rows=[]\n            for key,total in ov["top_games"]:\n                g=st.session_state.game_totals.get(key,{})\n                rows.append({\n                    "Rank":game_rank.get(key),\n                    "Game":f'{g.get("away","?")} @ {g.get("home","?")}',\n                    "Total":format_total_movement(total,opening_games.get(key))\n                })\n            gdf=pd.DataFrame(rows)\n            gst=gdf.style.map(movement_cell_style,subset=["Total"]) if hasattr(gdf.style,"map") else gdf.style.applymap(movement_cell_style,subset=["Total"])\n            st.dataframe(gst,hide_index=True,use_container_width=True)\n\n        with right:\n            st.markdown("#### Implied Team Total Rankings")\n            rows=[]\n            for team,imp in ov["top_teams"]:\n                game_key=None\n                for key,g in st.session_state.game_totals.items():\n                    if team in {g.get("away"),g.get("home")}:\n                        game_key=key\n                        break\n                rows.append({\n                    "Rank":team_rank.get(team),\n                    "Team":team,\n                    "Implied Total":format_total_movement(imp,opening_teams.get((game_key,team)))\n                })\n            tdf=pd.DataFrame(rows)\n            tst=tdf.style.map(movement_cell_style,subset=["Implied Total"]) if hasattr(tdf.style,"map") else tdf.style.applymap(movement_cell_style,subset=["Implied Total"])\n            st.dataframe(tst,hide_index=True,use_container_width=True)\n\n        st.caption("Movement in parentheses is versus the first sportsbook snapshot: green = increase, red = decrease. Ranks use only games and teams on the selected platform slate.")\n'''
if old_block in s:
    s=s.replace(old_block,new_block,1)
elif 'opening_games,opening_teams=opening_line_movements()' not in s:
    raise SystemExit('render block not found')

path.write_text(s,encoding='utf-8')
print('patched app.py')
